parameters:
  - name: image
    displayName: pool Image
    type: string
    default: ubuntu-latest
    values:
      - windows-latest
      - ubuntu-latest
      - macOs-latest
trigger: none

jobs :
- job : build
  displayName: my first build job
  pool:
      vmImage:${{paramters.image}}
  steps:
  - script: echo buulding $(Build.BuildNumber) with $(paramters.image)


